// Register user constants
export const REGISTER_USER_INIT = "REGISTER_USER_INIT";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const REGISTER_USER_RESET = "REGISTER_USER_RESET";

// login user constants
export const LOGIN_USER_INIT = "LOGIN_USER_INIT";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGIN_USER_RESET = "LOGIN_USER_RESET";

// Get user info
export const GET_USER_INFO_INIT = "GET_USER_INFO_INIT";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILED = "GET_USER_INFO_FAILED";
export const GET_USER_INFO_RESET = "GET_USER_INFO_RESET";
